stages:
  - deploy

deploy_to_railway:
  stage: deploy
  image: node:18
  script:
    - npm install -g @railway/cli
    - export RAILWAY_TOKEN=$RAILWAY_TOKEN
    - railway whoami
    - railway up --service $RAILWAY_SERVICE_ID --detach
  only:
    - main